---
cluster:
  name: desktop
  singleNode: true
  standalone: true # Please enable it only if you want to make a single-node cluster

# Bare-metal Driver Configuration
driver:
  nvidia:
    gpu:
      eula: true

# Enable SmartX features
features:
  - nvidia.com/gpu
  - org.ulagbulag.io/cni
  - org.ulagbulag.io/desktop-environment/vine

# Bare-metal Network Configuration
network:
  interface:
    mtu: 1500

  # Upstream dns servers
  nameservers:
    ns1: 1.1.1.1
    ns2: 8.8.8.8

vine:
  session:
    nodeSelector:
      node-role.kubernetes.io/kiss: ControlPlane
      node-role.kubernetes.io/standalone: "true"
